### ISSUE TITLE
Child Processes Still Running?

### ISSUE THREAD

**Issue by apowers313** [igorzoriy/gulp-html2pdf#2]
This module runs 3x faster and creates PDFs that are 10x smaller than [gulp-html-pdf](https://www.npmjs.com/package/gulp-html-pdf), but I'm having a problem with it: node doesn't terminate after running it on a series of files.

[wtfnode](https://www.npmjs.com/package/wtfnode) shows that there are a number of child processes still running and `ps aux` shows that there are a number of `/bin/sh -c wkhtmltopdf --quiet - - | cat` processes still pending.

Could it be that this plugin isn't closing the input pipe, so the processes don't die? Has anyone else seen this issue?

**Comment by igorzoriy** [comment]
Hi. Unfortunately I can't reproduce it on my mac. Anyway this plugin just use https://github.com/devongovett/node-wkhtmltopdf. You can check this issues at this repo.
